 export const sampleData = [
  {
    name: "Vegetable Korma",
    img: "Vegetable Korma.jpg",
    cat: "Dinner",
    price: 10.99,
    cost_price: 5.99,
    rating: 4.5,
    total_sales: 100,
    customer_id: 1,
    profit: 5
  },
  {
    name: "Vanilla Gelato",
    img: "Vanilla Gelato.jpg",
    cat: "Dessert",
    price: 6.99,
    cost_price: 3.99,
    rating: 4.7,
    total_sales: 150,
    customer_id: 2,
    profit: 3
  },
  {
    name: "Turkey and Wild Rice Soup",
    img: "Turkey and Wild Rice Soup.jpeg",
    cat: "Dinner",
    price: 8.99,
    cost_price: 4.99,
    rating: 4.2,
    total_sales: 80,
    customer_id: 3,
    profit: 4
  },
  {
    name: "Tikka Kebab",
    img: "Tikka Kebab.jpg",
    cat: "Starters",
    price: 12.99,
    cost_price: 7.99,
    rating: 4.8,
    total_sales: 120,
    customer_id: 4,
    profit: 5
  },
  {
    name: "Thomas Keller’s Coconut Cake",
    img: "Thomas Keller’s Coconut Cake.jpg",
    cat: "Dessert",
    price: 15.99,
    cost_price: 9.99,
    rating: 4.9,
    total_sales: 200,
    customer_id: 5,
    profit: 6
  },
  {
    name: "The Ultimate Chicken Noodle Soup",
    img: "The Ultimate Chicken Noodle Soup.jpg",
    cat: "Dinner",
    price: 9.99,
    cost_price: 5.49,
    rating: 4.4,
    total_sales: 90,
    customer_id: 6,
    profit: 4.5
  },
  {
    name: "Texas Sheet Cake",
    img: "Texas Sheet Cake.jpg",
    cat: "Dessert",
    price: 13.99,
    cost_price: 8.99,
    rating: 4.6,
    total_sales: 180,
    customer_id: 7,
    profit: 5
  },
  {
    name: "Tea",
    img: "Tea.jpg",
    cat: "Beverage",
    price: 3.99,
    cost_price: 1.99,
    rating: 4.3,
    total_sales: 50,
    customer_id: 8,
    profit: 2
  },
  {
    name: "Strawberry Rhubarb Cheesecake",
    img: "Strawberry Rhubarb Cheesecake.jpg",
    cat: "Dessert",
    price: 18.99,
    cost_price: 12.99,
    rating: 4.8,
    total_sales: 220,
    customer_id: 9,
    profit: 6
  },
  {
    name: "Sticky Baked Chicken Wings",
    img: "Sticky Baked Chicken Wings.jpg",
    cat: "Starters",
    price: 14.99,
    cost_price: 9.99,
    rating: 4.7,
    total_sales: 180,
    customer_id: 10,
    profit: 5
  },
  {
    name: "Stew",
    img: "Stew.jpg",
    cat: "Dinner",
    price: 12.99,
    cost_price: 8.49,
    rating: 4.4,
    total_sales: 160,
    customer_id: 11,
    profit: 4.5
  },
  {
    name: "Steak and Shrimp Kabobs",
    img: "Steak and Shrimp Kabobs.jpg",
    cat: "Lunch",
    price: 22.99,
    cost_price: 15.99,
    rating: 4.9,
    total_sales: 250,
    customer_id: 12,
    profit: 7
  },
  {
    name: "Steak and eggs",
    img: "Steak and eggs.jpg",
    cat: "Breakfast",
    price: 16.99,
    cost_price: 10.99,
    rating: 4.6,
    total_sales: 190,
    customer_id: 13,
    profit: 6
  },
  {
    name: "Steak",
    img: "Steak.jpg",
    cat: "Dinner",
    price: 25.99,
    cost_price: 18.99,
    rating: 4.8,
    total_sales: 280,
    customer_id: 14,
    profit: 7
  },
  {
    name: "Sprite",
    img: "Sprite.png",
    cat: "Beverage",
    price: 1.99,
    cost_price: 0.99,
    rating: 4.2,
    total_sales: 40,
    customer_id: 15,
    profit: 1
  },
  {
    name: "Spinach Artichoke Dip",
    img: "Spinach Artichoke Dip.jpg",
    cat: "Starters",
    price: 10.99,
    cost_price: 6.99,
    rating: 4.5,
    total_sales: 120,
    customer_id: 16,
    profit: 4
  },
  {
    name: "Spicy Thai Coconut Chicken Soup",
    img: "Spicy Thai Coconut Chicken Soup.jpg",
    cat: "Starters",
    price: 13.99,
    cost_price: 8.99,
    rating: 4.6,
    total_sales: 150,
    customer_id: 17,
    profit: 5
  },
  {
    name: "Soft and Chewy Chocolate Chip Cookies",
    img: "Soft and Chewy Chocolate Chip Cookies.jpg",
    cat: "Dessert",
    price: 9.99,
    cost_price: 5.99,
    rating: 4.3,
    total_sales: 100,
    customer_id: 18,
    profit: 4
  },
  {
    name: "Slow-Cooker Pork Loin",
    img: "Slow-Cooker Pork Loin.jpg",
    cat: "Lunch",
    price: 20.99,
    cost_price: 15.99,
    rating: 4.7,
    total_sales: 210,
    customer_id: 19,
    profit: 5
  },
  {
    name: "Shimla Mirch Qeema",
    img: "Shimla Mirch Qeema.jpg",
    cat: "Lunch",
    price: 14.99,
    cost_price: 10.99,
    rating: 4.5,
    total_sales: 180,
    customer_id: 20,
    profit: 4
  },
  {
    name: "SEWAIYAN",
    img: "SEWAIYAN.jpg",
    cat: "Dessert",
    price: 8.99,
    cost_price: 4.99,
    rating: 4.3,
    total_sales: 120,
    customer_id: 21,
    profit: 4
  },
  {
    name: "Samosa Chaat",
    img: "Samosa Chaat.jpg",
    cat: "Lunch",
    price: 9.99,
    cost_price: 5.99,
    rating: 4.4,
    total_sales: 130,
    customer_id: 22,
    profit: 4
  },
  {
    name: "SAGUDANA KHEER",
    img: "SAGUDANA KHEER.jpg",
    cat: "Dessert",
    price: 6.99,
    cost_price: 3.99,
    rating: 4.2,
    total_sales: 100,
    customer_id: 23,
    profit: 3
  },
  {
    name: "Saag Aloo (Spinach And Potato Curry)",
    img: "Saag Aloo (Spinach And Potato Curry).jpg",
    cat: "Lunch",
    price: 12.99,
    cost_price: 8.99,
    rating: 4.6,
    total_sales: 160,
    customer_id: 24,
    profit: 4
  },
  {
    name: "Saag",
    img: "Saag.jpg",
    cat: "Dinner",
    price: 11.99,
    cost_price: 7.99,
    rating: 4.5,
    total_sales: 150,
    customer_id: 25,
    profit: 4
  },
  {
    name: "Reuben sandwich",
    img: "Reuben sandwich.jpg",
    cat: "Breakfast",
    price: 13.99,
    cost_price: 9.99,
    rating: 4.7,
    total_sales: 170,
    customer_id: 26,
    profit: 4
  },
  {
    name: "Quick Cream of Mushroom Soup",
    img: "Quick Cream of Mushroom Soup.jpg",
    cat: "Starters",
    price: 7.99,
    cost_price: 4.99,
    rating: 4.3,
    total_sales: 110,
    customer_id: 27,
    profit: 3
  },
  {
    name: "Qeemay Wala Naan",
    img: "Qeemay Wala Naan.jpg",
    cat: "Lunch",
    price: 10.99,
    cost_price: 6.99,
    rating: 4.4,
    total_sales: 140,
    customer_id: 28,
    profit: 4
  },

  {
    name: "Pulao Rice",
    img: "Pulao Rice.jpg",
    cat: "Lunch",
    price: 11.99,
    cost_price: 7.99,
    rating: 4.6,
    total_sales: 160,
    customer_id: 29,
    profit: 4
  },
  {
    name: "Poutine",
    img: "Poutine.jpg",
    cat: "Starters",
    price: 8.99,
    cost_price: 5.99,
    rating: 4.3,
    total_sales: 130,
    customer_id: 30,
    profit: 3
  },
  {
    name: "Potato Puffs",
    img: "Potato Puffs.jpg",
    cat: "Starters",
    price: 7.99,
    cost_price: 4.99,
    rating: 4.2,
    total_sales: 120,
    customer_id: 31,
    profit: 3
  },
  {
    name: "Potato chips",
    img: "Potato chips.jpg",
    cat: "Lunch",
    price: 3.99,
    cost_price: 1.99,
    rating: 4.0,
    total_sales: 100,
    customer_id: 32,
    profit: 2
  },
  {
    name: "Poha",
    img: "Poha.jpg",
    cat: "Breakfast",
    price: 9.99,
    cost_price: 5.99,
    rating: 4.4,
    total_sales: 140,
    customer_id: 33,
    profit: 4
  },
  {
    name: "Pizza Monkey Bread",
    img: "Pizza Monkey Bread.jpg",
    cat: "Dinner",
    price: 13.99,
    cost_price: 8.99,
    rating: 4.7,
    total_sales: 170,
    customer_id: 34,
    profit: 5
  },
  {
    name: "Pittsburgh-Style Nut Roll",
    img: "Pittsburgh-Style Nut Roll.jpg",
    cat: "Dessert",
    price: 16.99,
    cost_price: 11.99,
    rating: 4.8,
    total_sales: 200,
    customer_id: 35,
    profit: 5
  },
  {
    name: "Pina Colada",
    img: "Pina Colada.jpg",
    cat: "Beverage",
    price: 7.99,
    cost_price: 3.99,
    rating: 4.5,
    total_sales: 150,
    customer_id: 36,
    profit: 4
  },
  {
    name: "Philly Cheesesteak",
    img: "Philly Cheesesteak.jpg",
    cat: "Lunch",
    price: 12.99,
    cost_price: 8.99,
    rating: 4.6,
    total_sales: 180,
    customer_id: 37,
    profit: 4
  },
  {
    name: "Pepsi",
    img: "pepsi.png",
    cat: "Beverage",
    price: 1.99,
    cost_price: 0.99,
    rating: 4.2,
    total_sales: 50,
    customer_id: 38,
    profit: 1
  },
  {
    name: "Peanut Butter Buckeyes",
    img: "Peanut Butter Buckeyes.jpeg",
    cat: "Dessert",
    price: 9.99,
    cost_price: 5.99,
    rating: 4.3,
    total_sales: 100,
    customer_id: 39,
    profit: 4
  },
  {
    name: "Peanut Butter Brownies",
    img: "Peanut Butter Brownies.jpg",
    cat: "Dessert",
    price: 12.99,
    cost_price: 8.99,
    rating: 4.5,
    total_sales: 120,
    customer_id: 40,
    profit: 4
  },
  {
    name: "Paya",
    img: "Paya.jpg",
    cat: "Lunch",
    price: 18.99,
    cost_price: 14.99,
    rating: 4.8,
    total_sales: 200,
    customer_id: 41,
    profit: 4
  },
  {
    name: "Pasta",
    img: "Pasta.jpeg",
    cat: "Lunch",
    price: 14.99,
    cost_price: 10.99,
    rating: 4.6,
    total_sales: 180,
    customer_id: 42,
    profit: 4
  },
  {
    name: "Paratha",
    img: "Paratha.jpg",
    cat: "Breakfast",
    price: 8.99,
    cost_price: 4.99,
    rating: 4.4,
    total_sales: 160,
    customer_id: 43,
    profit: 4
  },
  {
    name: "Paneer Tikka Masala",
    img: "Paneer Tikka Masala.jpg",
    cat: "Dinner",
    price: 15.99,
    cost_price: 11.99,
    rating: 4.7,
    total_sales: 190,
    customer_id: 44,
    profit: 4
  },
  {
    name: "Pancakes",
    img: "Pancakes.jpg",
    cat: "Breakfast",
    price: 10.99,
    cost_price: 6.99,
    rating: 4.5,
    total_sales: 170,
    customer_id: 45,
    profit: 4
  },
  {
    name: "Orange juice",
    img: "Orange juice.jpg",
    cat: "Beverage",
    price: 4.99,
    cost_price: 2.99,
    rating: 4.2,
    total_sales: 150,
    customer_id: 46,
    profit: 2
  },
  {
    name: "Nova Scotian Lobster Rolls",
    img: "Nova Scotian Lobster Rolls.jpg",
    cat: "Dinner",
    price: 22.99,
    cost_price: 18.99,
    rating: 4.9,
    total_sales: 250,
    customer_id: 47,
    profit: 4
  },
  {
    name: "Nihari",
    img: "Nihari.jpg",
    cat: "Dinner",
    price: 17.99,
    cost_price: 13.99,
    rating: 4.8,
    total_sales: 220,
    customer_id: 48,
    profit: 4
  },
  {
    name: "Italian Sausage and Zucchini Soup",
    img: "Italian Sausage and Zucchini Soup.jpg",
    cat: "Dinner",
    price: 14.99,
    cost_price: 10.99,
    rating: 4.5,
    total_sales: 180,
    customer_id: 59,
    profit: 4
  },
  {
    name: "Hungarian Chicken Paprikash",
    img: "Hungarian Chicken Paprikash.jpeg",
    cat: "Lunch",
    price: 16.99,
    cost_price: 12.99,
    rating: 4.6,
    total_sales: 190,
    customer_id: 60,
    profit: 4
  },
  {
    name: "Hershey's Chocolate Cake",
    img: "Hershey's Chocolate Cake.jpg",
    cat: "Dessert",
    price: 19.99,
    cost_price: 15.99,
    rating: 4.8,
    total_sales: 210,
    customer_id: 61,
    profit: 4
  },
  {
    name: "Halwa Puri",
    img: "Halwa Puri.jpg",
    cat: "Breakfast",
    price: 12.99,
    cost_price: 8.99,
    rating: 4.3,
    total_sales: 160,
    customer_id: 62,
    profit: 4
  },
  {
    name: "Haleem",
    img: "Haleem.jpg",
    cat: "Dinner",
    price: 17.99,
    cost_price: 13.99,
    rating: 4.7,
    total_sales: 200,
    customer_id: 63,
    profit: 4
  },
  {
    name: "Fruit salad",
    img: "Fruit salad.jpg",
    cat: "Starters",
    price: 10.99,
    cost_price: 6.99,
    rating: 4.2,
    total_sales: 140,
    customer_id: 64,
    profit: 4
  },
  {
    name: "French Toast",
    img: "French Toast.jpg",
    cat: "Breakfast",
    price: 8.99,
    cost_price: 4.99,
    rating: 4.0,
    total_sales: 120,
    customer_id: 65,
    profit: 4
  },
  {
    name: "Fanta",
    img: "Fanta.png",
    cat: "Beverage",
    price: 2.99,
    cost_price: 1.99,
    rating: 4.1,
    total_sales: 130,
    customer_id: 66,
    profit: 3
  },
  {
    name: "Fajitas",
    img: "Fajitas.jpg",
    cat: "Dinner",
    price: 15.99,
    cost_price: 11.99,
    rating: 4.4,
    total_sales: 170,
    customer_id: 67,
    profit: 4
  },
  {
    name: "Egg Drop Soup",
    img: "Egg Drop Soup.jpg",
    cat: "Starters",
    price: 7.99,
    cost_price: 3.99,
    rating: 4.0,
    total_sales: 110,
    customer_id: 68,
    profit: 4
  },
  {
    name: "Easy Beef Soup",
    img: "Easy Beef Soup.jpeg",
    cat: "Dinner",
    price: 12.99,
    cost_price: 8.99,
    rating: 4.4,
    total_sales: 170,
    customer_id: 69,
    profit: 4
  },
  {
    name: "Dosa",
    img: "Dosa.jpg",
    cat: "Breakfast",
    price: 10.99,
    cost_price: 6.99,
    rating: 4.3,
    total_sales: 160,
    customer_id: 70,
    profit: 4
  },
  {
    name: "Dorie Greenspan’s Chocolate Chunker Cookies",
    img: "Dorie Greenspan’s Chocolate Chunker Cookies.jpg",
    cat: "Dessert",
    price: 9.99,
    cost_price: 5.99,
    rating: 4.2,
    total_sales: 150,
    customer_id: 71,
    profit: 4
  },
  {
    name: "Creamy Chicken Rice Soup",
    img: "Creamy Chicken Rice Soup.jpg",
    cat: "Lunch",
    price: 11.99,
    cost_price: 7.99,
    rating: 4.3,
    total_sales: 160,
    customer_id: 72,
    profit: 4
  },
  {
    name: "Cream Cheese Fruit Dip",
    img: "Cream Cheese Fruit Dip.jpg",
    cat: "Starters",
    price: 8.99,
    cost_price: 4.99,
    rating: 4.1,
    total_sales: 140,
    customer_id: 73,
    profit: 4
  },
  {
    name: "Coke",
    img: "Coke.png",
    cat: "Beverage",
    price: 1.99,
    cost_price: 0.99,
    rating: 4.0,
    total_sales: 120,
    customer_id: 74,
    profit: 3
  },
  {
    name: "Coffee",
    img: "Coffee.jpg",
    cat: "Beverage",
    price: 3.99,
    cost_price: 1.99,
    rating: 4.1,
    total_sales: 130,
    customer_id: 75,
    profit: 3
  },
  {
    name: "Classic hot dog",
    img: "Classic hot dog.jpg",
    cat: "Lunch",
    price: 6.99,
    cost_price: 3.99,
    rating: 4.0,
    total_sales: 110,
    customer_id: 76,
    profit: 3
  },
  {
    name: "Classic Carrot Cake",
    img: "Classic Carrot Cake.jpg",
    cat: "Dessert",
    price: 14.99,
    cost_price: 10.99,
    rating: 4.5,
    total_sales: 180,
    customer_id: 77,
    profit: 4
  },
  {
    name: "Chocolate Pudding Pie",
    img: "Chocolate Pudding Pie.jpeg",
    cat: "Dessert",
    price: 13.99,
    cost_price: 9.99,
    rating: 4.4,
    total_sales: 170,
    customer_id: 78,
    profit: 4
  },
  {
    name: "Chicken Zeera Bites",
    img: "Chicken Zeera Bites.jpg",
    cat: "Starters",
    price: 9.99,
    cost_price: 5.99,
    rating: 4.2,
    total_sales: 150,
    customer_id: 79,
    profit: 4
  },
  {
    name: "Chicken Fried Steaks",
    img: "Chicken Fried Steaks.jpg",
    cat: "Dinner",
    price: 16.99,
    cost_price: 12.99,
    rating: 4.7,
    total_sales: 200,
    customer_id: 80,
    profit: 4
  },
  {
    name: "Chicken Barley Soup",
    img: "Chicken Barley Soup.jpg",
    cat: "Starters",
    price: 11.99,
    cost_price: 7.99,
    rating: 4.4,
    total_sales: 170,
    customer_id: 81,
    profit: 4
  },
  {
    name: "Chicken and Waffles Sandwich",
    img: "Chicken and Waffles Sandwich.jpg",
    cat: "Breakfast",
    price: 14.99,
    cost_price: 10.99,
    rating: 4.6,
    total_sales: 190,
    customer_id: 82,
    profit: 4
  },
  {
    name: "Chicken and Gravy",
    img: "Chicken and Gravy.jpg",
    cat: "Dinner",
    price: 15.99,
    cost_price: 11.99,
    rating: 4.6,
    total_sales: 180,
    customer_id: 83,
    profit: 4
  },
  {
    name: "Cheesy Cream of Asparagus Soup",
    img: "Cheesy Cream of Asparagus Soup.jpg",
    cat: "Starters",
    price: 12.99,
    cost_price: 8.99,
    rating: 4.5,
    total_sales: 180,
    customer_id: 84,
    profit: 4
  },
  {
    name: "Cheesecake",
    img: "Cheesecake.jpg",
    cat: "Dessert",
    price: 19.99,
    cost_price: 15.99,
    rating: 4.8,
    total_sales: 220,
    customer_id: 85,
    profit: 4
  },
  {
    name: "Cheeseburger Soup",
    img: "Cheeseburger Soup.jpg",
    cat: "Starters",
    price: 13.99,
    cost_price: 9.99,
    rating: 4.5,
    total_sales: 190,
    customer_id: 86,
    profit: 4
  },
  {
    name: "Cheddar Potato Chowder",
    img: "Cheddar Potato Chowder.jpg",
    cat: "Starters",
    price: 14.99,
    cost_price: 10.99,
    rating: 4.6,
    total_sales: 200,
    customer_id: 87,
    profit: 4
  },
  {
    name: "Bun Kebab",
    img: "Bun Kebab.jpg",
    cat: "Dinner",
    price: 12.99,
    cost_price: 8.99,
    rating: 4.4,
    total_sales: 170,
    customer_id: 88,
    profit: 4
  },
  {
    name: "Broccoli-Stuffed Chicken",
    img: "Broccoli-Stuffed Chicken.jpg",
    cat: "Dinner",
    price: 17.99,
    cost_price: 13.99,
    rating: 4.7,
    total_sales: 210,
    customer_id: 89,
    profit: 4
  },
  {
    name: "Breakfast Wrap",
    img: "Breakfast Wrap.jpg",
    cat: "Breakfast",
    price: 8.99,
    cost_price: 4.99,
    rating: 4.2,
    total_sales: 150,
    customer_id: 90,
    profit: 4
  },
  {
    name: "Breakfast Sausage",
    img: "Breakfast Sausage.jpg",
    cat: "Breakfast",
    price: 6.99,
    cost_price: 3.99,
    rating: 4.0,
    total_sales: 120,
    customer_id: 91,
    profit: 3
  },
  {
    name: "Breakfast Sandwich",
    img: "Breakfast Sandwich.jpg",
    cat: "Breakfast",
    price: 7.99,
    cost_price: 4.99,
    rating: 4.1,
    total_sales: 130,
    customer_id: 92,
    profit: 3
  },
  {
    name: "Bread Pudding",
    img: "Bread Pudding.jpg",
    cat: "Dessert",
    price: 10.99,
    cost_price: 6.99,
    rating: 4.3,
    total_sales: 160,
    customer_id: 93,
    profit: 4
  },
  {
    name: "Boston Cream Pie",
    img: "Boston Cream Pie.jpg",
    cat: "Dessert",
    price: 12.99,
    cost_price: 8.99,
    rating: 4.5,
    total_sales: 180,
    customer_id: 94,
    profit: 4
  },
  {
    name: "Biryani",
    img: "Biryani.jpg",
    cat: "Dinner",
    price: 18.99,
    cost_price: 14.99,
    rating: 4.7,
    total_sales: 200,
    customer_id: 95,
    profit: 4
  },
  {
    name: "Beer",
    img: "beer.png",
    cat: "Beverage",
    price: 3.99,
    cost_price: 1.99,
    rating: 4.1,
    total_sales: 140,
    customer_id: 96,
    profit: 3
  },
  {
    name: "Beef jerky",
    img: "Beef jerky.jpg",
    cat: "Starters",
    price: 9.99,
    cost_price: 5.99,
    rating: 4.2,
    total_sales: 150,
    customer_id: 97,
    profit: 4
  },
  {
    name: "Beef and Mushrooms with Smashed Potatoes",
    img: "Beef and Mushrooms with Smashed Potatoes.jpg",
    cat: "Lunch",
    price: 16.99,
    cost_price: 12.99,
    rating: 4.6,
    total_sales: 190,
    customer_id: 98,
    profit: 4
  },
  {
    name: "Barbecue Ribs",
    img: "Barbecue Ribs.jpg",
    cat: "Lunch",
    price: 20.99,
    cost_price: 16.99,
    rating: 4.8,
    total_sales: 220,
    customer_id: 99,
    profit: 4
  },
  {
    name: "Bananas Foster",
    img: "Bananas Foster.jpg",
    cat: "Dessert",
    price: 14.99,
    cost_price: 10.99,
    rating: 4.4,
    total_sales: 170,
    customer_id: 100,
    profit: 4
  },
  {
    name: "Baked, Grilled, Fried Chicken",
    img: "baked-grilled-fried chicken.jpg",
    cat: "Dinner",
    price: 15.99,
    cost_price: 11.99,
    rating: 4.5,
    total_sales: 180,
    customer_id: 101,
    profit: 4
  },
  {
    name: "Baked Alaska",
    img: "Baked Alaska.jpeg",
    cat: "Dessert",
    price: 22.99,
    cost_price: 18.99,
    rating: 4.9,
    total_sales: 250,
    customer_id: 102,
    profit: 4
  },
  {
    name: "Baba Ghanoush 3 Ways",
    img: "Baba Ghanoush 3 Ways.jpg",
    cat: "Starters",
    price: 11.99,
    cost_price: 7.99,
    rating: 4.3,
    total_sales: 160,
    customer_id: 103,
    profit: 4
  },
  {
    name: "Avocado Toast",
    img: "Avocado Toast.jpeg",
    cat: "Breakfast",
    price: 9.99,
    cost_price: 5.99,
    rating: 4.2,
    total_sales: 150,
    customer_id: 104,
    profit: 4
  },
  {
    name: "Apple Pie",
    img: "Apple Pie.jpg",
    cat: "Dessert",
    price: 12.99,
    cost_price: 8.99,
    rating: 4.3,
    total_sales: 170,
    customer_id: 105,
    profit: 4
  },
  {
    name: "Aloo Paratha",
    img: "Aloo Paratha.jpg",
    cat: "Breakfast",
    price: 10.99,
    cost_price: 6.99,
    rating: 4.1,
    total_sales: 140,
    customer_id: 106,
    profit: 4
  },
  {
    name: "Aloo Baingan (Eggplant and Potato Curry)",
    img: "Aloo Baingan (Eggplant and Potato Curry).jpg",
    cat: "Dinner",
    price: 14.99,
    cost_price: 10.99,
    rating: 4.4,
    total_sales: 180,
    customer_id: 107,
    profit: 4
  }
];

