[
  {
    "name": "Bob Brown",
    "email": "bob.brown@example.com",
    "phone": 5559876543,
    "password": "$2b$10$gsp9W/IVAuGxOJNwLTn7hehH9kh9K2znZRasPKZ355oSZZ8j9m4RC",
    "all_orders": [],
    "delivered_order": [],
    "assigned_order": [],
    "rating": 4,
    "current_order": [],
    "rejected_order": []
  },
  {
    "name": "Emily Davis",
    "email": "emily.davis@example.com",
    "phone": 5557891234,
    "password": "$2b$10$eL8d265/Q87.HYp2bcmjy.0qc6S2dBDXNNY1PD64tC2yywrzFWl1q",
    "all_orders": [],
    "delivered_order": [],
    "assigned_order": [],
    "rating": 3,
    "current_order": [],
    "rejected_order": []
  },
  {
    "name": "Michael Wilson",
    "email": "michael.wilson@example.com",
    "phone": 5554567890,
    "password": "$2b$10$udYqQ./ygO8flZSUThZ4B.kDxfeKvECFbhbbVj3tdPO7RPU90oqKu",
    "all_orders": [],
    "delivered_order": [],
    "assigned_order": [],
    "rating": 2,
    "current_order": [],
    "rejected_order": []
  },
  {
    "name": "Sarah Taylor",
    "email": "sarah.taylor@example.com",
    "phone": 5553219876,
    "password": "$2b$10$aEU6VBaz4sco.dUn7ZRTT.oRLvJvq3DC44dZ7uewHJRIApP6Fx38G",
    "all_orders": [],
    "delivered_order": [],
    "assigned_order": [],
    "rating": 4,
    "current_order": [],
    "rejected_order": []
  },
  {
    "name": "David Martinez",
    "email": "david.martinez@example.com",
    "phone": 5558765432,
    "password": "$2b$10$pVwYRMyYLoOUkJj3U4pCQuMRcBVJKxYeeLDDF7G3Wyvd41vsAhfHm",
    "all_orders": [],
    "delivered_order": [],
    "assigned_order": [],
    "rating": 3,
    "current_order": [],
    "rejected_order": []
  },
  {
    "name": "Jessica Anderson",
    "email": "jessica.anderson@example.com",
    "phone": 5552345678,
    "password": "$2b$10$OtmGLsBzjY7Ine1Lw9Yl0eA5MbezTx1bYpDZaI62GXRq56Tp038ky",
    "all_orders": [],
    "delivered_order": [],
    "assigned_order": [],
    "rating": 2,
    "current_order": [],
    "rejected_order": []
  },
  {
    "name": "Christopher Thompson",
    "email": "christopher.thompson@example.com",
    "phone": 5556789012,
    "password": "$2b$10$Tx6AaY.0mX6GqIJ1JekGEulWJLsad5vcVxK4nuAtfCw8cBWbf4rve",
    "all_orders": [],
    "delivered_order": [],
    "assigned_order": [],
    "rating": 4,
    "current_order": [],
    "rejected_order": []
  },
  {
    "name": "Amanda White",
    "email": "amanda.white@example.com",
    "phone": 5558901234,
    "password": "$2b$10$5Xbjva3F.Iv3IhRAoPvGqe3kWlr7V5oNwS73lgsqmpbD9hqa2N9U.",
    "all_orders": [],
    "delivered_order": [],
    "assigned_order": [],
    "rating": 3,
    "current_order": [],
    "rejected_order": []
  },
  {
    "name": "Matthew Garcia",
    "email": "matthew.garcia@example.com",
    "phone": 5551234567,
    "password": "$2b$10$FpfXRDbPtgHT2/iQel/Ll.6XrWt6KN3ULm6ACKIgG2RfkliXQWVQG",
    "all_orders": [],
    "delivered_order": [],
    "assigned_order": [],
    "rating": 2,
    "current_order": [],
    "rejected_order": []
  },
  {
    "name": "Ashley Hernandez",
    "email": "ashley.hernandez@example.com",
    "phone": 5559876543,
    "password": "$2b$10$Ue5toBDmDzLwcfcq/5xAO.PyYHhfGLtt1zrADTjGH/GVsWiN0bL1G",
    "all_orders": [],
    "delivered_order": [],
    "assigned_order": [],
    "rating": 4,
    "current_order": [],
    "rejected_order": []
  },
  {
    "name": "John Doe",
    "email": "john.doe@example.com",
    "phone": 1234567890,
    "password": "$2b$10$5hcGd4iGbmC19CZXZNTFoOg6.VdFIntBtSezCTOoJZhHUq6QRQcU6",
    "all_orders": [],
    "delivered_order": [],
    "assigned_order": [],
    "rating": 4,
    "current_order": [],
    "rejected_order": []
  },
  {
    "name": "Jane Smith",
    "email": "jane.smith@example.com",
    "phone": 9876543210,
    "password": "$2b$10$Ev.JRK8MF90yYhHXPu.XO.lK8ivdjYjsGU1wRLqN0fIApNBeI5H6a",
    "all_orders": [],
    "delivered_order": [],
    "assigned_order": [],
    "rating": 3,
    "current_order": [],
    "rejected_order": []
  },
  {
    "name": "Alice Johnson",
    "email": "alice.johnson@example.com",
    "phone": 5551234567,
    "password": "$2b$10$sHzTvGjedVBXPTfofnIfhekTGWA8s5wTP/DBYIt3j9wNP4y.3Sowy",
    "all_orders": [],
    "delivered_order": [],
    "assigned_order": [],
    "rating": 2,
    "current_order": [],
    "rejected_order": []
  }
]
